/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin: https://github.com/Baalgarthem
*/

var L = Object.defineProperty;
var I = Object.getOwnPropertyDescriptor;
var $ = Object.getOwnPropertyNames;
var P = Object.prototype.hasOwnProperty;
var V = (p, h) => {
  for (var e in h) L(p, e, { get: h[e], enumerable: !0 });
};
var j = (p, h, e, s) => {
  if ((h && typeof h == "object") || typeof h == "function")
    for (let l of $(h))
      !P.call(p, l) &&
        l !== e &&
        L(p, l, { get: () => h[l], enumerable: !(s = I(h, l)) || s.enumerable });
  return p;
};
var D = (p) => j(L({}, "__esModule", { value: !0 }), p);
var N = {};
V(N, { default: () => b });
module.exports = D(N);

var u = require("obsidian");

/* ── Translations ──────────────────────────────────────────────── */
var TRANSLATIONS = {
  es: {
    // Language setting
    langSettingName: "Idioma / Language",
    langSettingDesc: "Idioma de la interfaz de configuración.",
    langEs: "Español",
    langEn: "English",

    // Sections
    sectionAppearance: "Apariencia del Árbol",
    sectionTitle:      "Línea de Título",
    sectionHover:      "Efectos al Pasar el Cursor",

    // Tree style
    treeStyleName: "Estilo de ramas",
    treeStyleDesc: "Elige el estilo visual de los conectores del árbol. Los cambios se aplican de inmediato.",
    styleClassic:   "Clásico      (├──, └──, │)",
    styleRounded:   "Redondeado   (├──, ╰──, │)",
    styleHeavy:     "Grueso       (┣━━, ┗━━, ┃)",
    styleDouble:    "Doble Línea  (╠══, ╚══, ║)",
    styleDotted:    "Punteado     (├──, └──, ┊)",
    styleSlim:      "Fino Dashed  (├╌╌, └╌╌, ╎)",
    styleAsciiplus: "ASCII Plus   (+--,  +--,  |)",
    styleArrows:    "Flechas      (╞══, ╘══, │)",

    // Connector dashes
    dashCountName: "Número de guiones",
    dashCountDesc: "Cuántos caracteres de guión siguen a cada símbolo de rama.",

    // Auto-slash
    autoSlashName: "Añadir / a carpetas",
    autoSlashDesc: "Agrega una barra diagonal a los elementos que tienen hijos.",

    // Title format
    titleFormatName:   "Formatear primera línea como título",
    titleFormatDesc:   "Aplica mayor tamaño de fuente y espaciado configurable a la primera línea del bloque.",
    titleSpacingName:  "Espaciado inferior del título (px)",
    titleSpacingDesc:  "Espacio entre la línea de título y el primer elemento del árbol. 0 = casi juntos.",

    // Hover
    hoverEnableName:  "Activar efecto al pasar el cursor",
    hoverEnableDesc:  "Resalta enlaces nativos de Obsidian y de Virtual Linker al pasar el cursor.",
    hoverStyleName:   "Estilo del hover",
    hoverStyleDesc:   "Efecto visual aplicado a los enlaces al pasar el cursor. Cambios inmediatos.",
    hoverBold:      "✦ Negrita — texto en negrita",
    hoverBorder:    "⬜ Borde — recuadro de contorno",
    hoverUnderline: "― Subrayado — subrayado animado",
    hoverHighlight: "🖊 Marcador — fondo de marcador de texto",
    hoverGlow:      "✦ Iluminación — resplandor suave",
    hoverPill:      "💊 Pastilla — fondo de color sólido",
    hoverNeon:      "⚡ Neón — brillo neón",
    hoverGhost:     "👻 Fantasma — marco punteado sutil",
    hoverBoldglow:  "✨ Negrita + Brillo — combinado",
  },
  en: {
    // Language setting
    langSettingName: "Idioma / Language",
    langSettingDesc: "Settings interface language.",
    langEs: "Español",
    langEn: "English",

    // Sections
    sectionAppearance: "Tree Appearance",
    sectionTitle:      "Title Line",
    sectionHover:      "Link Hover Effects",

    // Tree style
    treeStyleName: "Tree branch style",
    treeStyleDesc: "Choose the visual style for branch connectors. Changes apply immediately to all rendered trees.",
    styleClassic:   "Classic      (├──, └──, │)",
    styleRounded:   "Rounded      (├──, ╰──, │)",
    styleHeavy:     "Heavy        (┣━━, ┗━━, ┃)",
    styleDouble:    "Double Line  (╠══, ╚══, ║)",
    styleDotted:    "Dotted Stem  (├──, └──, ┊)",
    styleSlim:      "Slim Dashed  (├╌╌, └╌╌, ╎)",
    styleAsciiplus: "ASCII Plus   (+--,  +--,  |)",
    styleArrows:    "Arrows       (╞══, ╘══, │)",

    // Connector dashes
    dashCountName: "Connector dashes",
    dashCountDesc: "Sets how many dash/connector characters follow each branch symbol.",

    // Auto-slash
    autoSlashName: "Auto-append / to folders",
    autoSlashDesc: "Automatically add a trailing slash to items that have children.",

    // Title format
    titleFormatName:  "Format first line as title",
    titleFormatDesc:  "Style the first line with larger text and configurable bottom spacing.",
    titleSpacingName: "Title bottom spacing (px)",
    titleSpacingDesc: "Space between the title line and the first tree element. 0 = almost touching.",

    // Hover
    hoverEnableName:  "Enable link hover effect",
    hoverEnableDesc:  "Highlight native Obsidian links and Virtual Linker links on mouse hover.",
    hoverStyleName:   "Link hover style",
    hoverStyleDesc:   "Visual effect applied to links on mouse hover. Changes apply instantly.",
    hoverBold:      "✦ Bold — bold text",
    hoverBorder:    "⬜ Border — outline box",
    hoverUnderline: "― Underline — animated underline",
    hoverHighlight: "🖊 Highlight — text marker background",
    hoverGlow:      "✦ Glow — soft glow",
    hoverPill:      "💊 Pill — solid color background",
    hoverNeon:      "⚡ Neon — neon glow",
    hoverGhost:     "👻 Ghost — subtle dashed frame",
    hoverBoldglow:  "✨ Bold + Glow — combined",
  }
};

/* ── Branch style definitions ──────────────────────────────────── */
var STYLES = {
  classic:   { branch: "├", last: "└", dash: "─", stem: "│" },
  rounded:   { branch: "├", last: "╰", dash: "─", stem: "│" },
  heavy:     { branch: "┣", last: "┗", dash: "━", stem: "┃" },
  double:    { branch: "╠", last: "╚", dash: "═", stem: "║" },
  dotted:    { branch: "├", last: "└", dash: "─", stem: "┊" },
  slim:      { branch: "├", last: "└", dash: "╌", stem: "╎" },
  asciiplus: { branch: "+", last: "+", dash: "-", stem: "|" },
  arrows:    { branch: "╞", last: "╘", dash: "═", stem: "│" }
};

/* ── Default settings ──────────────────────────────────────────── */
var W = {
  language: "es",
  dashCount: 2,
  autoAppendSlash: !1,
  treeStyle: "classic",
  enableLinkHover: !0,
  linkHoverStyle: "bold",
  enableTitleFormat: !0,
  titleFontSize: "1.15em",
  titleSpacing: 12
};

/* ── Plugin class ──────────────────────────────────────────────── */
var b = class extends u.Plugin {
  constructor() {
    super(...arguments);
    this.renderedBlocks = new Map();

    this.treeProcessor = (sourceText, containerEl, ctx) => {
      this.renderedBlocks.set(containerEl, sourceText);
      this._renderTree(sourceText, containerEl, ctx);
    };
  }

  /* Shorthand translation helper */
  t(key) {
    let lang = this.settings.language || "es";
    let dict = TRANSLATIONS[lang] || TRANSLATIONS.es;
    return dict[key] || TRANSLATIONS.es[key] || key;
  }

  /* Core tree render */
  _renderTree(sourceText, containerEl, ctx) {
    var B;
    let { autoAppendSlash: o } = this.settings;
    let a = this.settings.dashCount;

    if (ctx && ctx.getSectionInfo) {
      let i = ctx.getSectionInfo(containerEl);
      if (i) {
        let c = i.text.split("\n")[i.lineStart].match(/^`{3,}tree\s+(\d+)\s*$/i);
        if (c) {
          let g = parseInt(c[1], 10);
          g >= 1 && g <= 10 && (a = g);
        }
      }
    }

    let styleKey = this.settings.treeStyle || "classic";
    let sym = STYLES[styleKey] || STYLES.classic;

    let r = sym.dash.repeat(a),
      t = sym.branch + r + " ",
      S = sym.last + r + " ",
      w = sym.stem + " ".repeat(a + 1),
      A = " ".repeat(a + 2),
      T = sourceText.split("\n"),
      v = 1 / 0;

    for (let n of T)
      if (n.trim() !== "") {
        let c = n.match(/^([\t ]*)/);
        c && c[1].length < v && (v = c[1].length);
      }

    let C = "";
    v !== 1 / 0 &&
      v > 0 &&
      (C = ((B = T.find((n) => n.trim() !== "")) == null ? void 0 : B.slice(0, v)) || "");

    let m = T.map((n) => (n.startsWith(C) ? n.slice(C.length) : n)).map((n) => {
      let c = n.match(/^([\t ]*)((?:[-*+─—–‒•⁃])|\d+\.)\s+(.*)$/);
      if (c) {
        let f = c[1],
          k = (f.match(/\t/g) || []).length,
          d = (f.match(/ /g) || []).length,
          x = k + Math.floor(d / 4);
        return x++, { level: x, leadingWhitespace: "", text: c[3] };
      }
      let g = n.match(/^(=+)\s?(.*)$/);
      return g
        ? { level: g[1].length, leadingWhitespace: "", text: g[2] }
        : { level: 0, leadingWhitespace: "", text: n };
    });

    let y = [];
    let M = m
      .map((n, c) => {
        let g = !0;
        for (let d = c + 1; d < m.length && !(m[d].level < n.level); d++)
          if (m[d].level === n.level) { g = !1; break; }
        y[n.level] = g;
        y.length = n.level + 1;
        let f = "";
        for (let d = 1; d < n.level; d++) f += y[d] ? A : w;
        n.level > 0 && (f += g ? S : t);
        let k = n.text;
        o &&
          n.level > 0 &&
          c + 1 < m.length &&
          m[c + 1].level > n.level &&
          !k.endsWith("/") &&
          (k += "/");
        return `${C}${n.leadingWhitespace}${f}${k}`;
      })
      .join("\n");

    containerEl.empty();
    let preEl = containerEl.createEl("pre");
    preEl.addClass("ascii-tree-block");

    if (this.settings.enableLinkHover) {
      preEl.addClass("ascii-tree-hover-" + (this.settings.linkHoverStyle || "bold"));
    }

    let codeEl = preEl.createEl("code");
    let noteMap = this.getVaultNoteMap();
    let ls = M.split("\n");

    for (let j = 0; j < ls.length; j++) {
      let sp = codeEl.createEl("span");
      let lineText = ls[j];

      if (j === 0 && this.settings.enableTitleFormat) {
        sp.addClass("ascii-tree-title");
        sp.setAttribute("data-spacing", String(this.settings.titleSpacing ?? 12));
        sp.style.fontSize = "var(--ascii-tree-title-font-size, " + (this.settings.titleFontSize || "1.15em") + ")";
        sp.style.marginBottom = "var(--ascii-tree-title-margin-bottom, 12px)";
      }

      this.renderLineContent(sp, lineText, noteMap);

      if (j < ls.length - 1) {
        codeEl.appendChild(document.createTextNode("\n"));
      }
    }
  }

  applyCSSVars() {
    let root = document.documentElement;
    let spacing = this.settings.titleSpacing ?? 12;
    root.style.setProperty("--ascii-tree-title-font-size", this.settings.titleFontSize || "1.15em");
    root.style.setProperty("--ascii-tree-title-margin-bottom", spacing + "px");
  }

  rerenderAllBlocks() {
    for (let [containerEl, sourceText] of this.renderedBlocks) {
      if (!containerEl.isConnected) {
        this.renderedBlocks.delete(containerEl);
        continue;
      }
      this._renderTree(sourceText, containerEl, null);
    }
  }

  updateHoverClasses() {
    let allPre = document.querySelectorAll("pre.ascii-tree-block");
    for (let pre of allPre) {
      let toRemove = Array.from(pre.classList).filter(c => c.startsWith("ascii-tree-hover-"));
      toRemove.forEach(c => pre.classList.remove(c));
      if (this.settings.enableLinkHover) {
        pre.classList.add("ascii-tree-hover-" + (this.settings.linkHoverStyle || "bold"));
      }
    }
  }

  getVaultNoteMap() {
    let noteMap = new Map();
    try {
      if (!this.app || !this.app.vault) return noteMap;
      let files = this.app.vault.getMarkdownFiles ? this.app.vault.getMarkdownFiles() : [];
      for (let file of files) {
        let title = file.basename;
        if (title) noteMap.set(title.toLowerCase(), { display: title, target: file.path });
        let cache = this.app.metadataCache ? this.app.metadataCache.getFileCache(file) : null;
        if (cache && cache.frontmatter && cache.frontmatter.aliases) {
          let aliases = cache.frontmatter.aliases;
          if (typeof aliases === "string") aliases = [aliases];
          if (Array.isArray(aliases)) {
            for (let alias of aliases) {
              if (typeof alias === "string" && alias.trim()) {
                noteMap.set(alias.trim().toLowerCase(), { display: alias.trim(), target: file.path });
              }
            }
          }
        }
      }
    } catch (err) {
      console.error("[ASCII Tree EX] Error building vault note map:", err);
    }
    return noteMap;
  }

  renderLineContent(container, text, noteMap) {
    let wikiLinkRegex = /\[\[([^\]\|]+)(?:\|([^\]]+))?\]\]|\[([^\]]+)\]\(([^\)]+)\)/g;
    let lastIndex = 0;
    let match;

    let processPlainSegment = (plainText) => {
      if (!plainText) return;
      if (!noteMap || noteMap.size === 0) {
        container.appendChild(document.createTextNode(plainText));
        return;
      }
      let keys = Array.from(noteMap.keys()).sort((a, b) => b.length - a.length);
      if (keys.length === 0) {
        container.appendChild(document.createTextNode(plainText));
        return;
      }
      let escaped = keys.map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
      let pattern = new RegExp("(?<![\\w\\[])" + "(" + escaped.join("|") + ")" + "(?![\\w\\]])", "gi");
      let segLastIndex = 0;
      let m;
      while ((m = pattern.exec(plainText)) !== null) {
        if (m.index > segLastIndex) {
          container.appendChild(document.createTextNode(plainText.substring(segLastIndex, m.index)));
        }
        let matchedText = m[0];
        let info = noteMap.get(matchedText.toLowerCase());
        if (!info) {
          container.appendChild(document.createTextNode(matchedText));
          segLastIndex = pattern.lastIndex;
          continue;
        }
        let target = info.target;
        let a = container.createEl("a", {
          text: matchedText,
          cls: "internal-link glossary-link",
          attr: { "data-href": target, href: target }
        });
        a.addEventListener("click", (evt) => {
          evt.preventDefault();
          this.app.workspace.openLinkText(target, "", evt.metaKey || evt.ctrlKey);
        });
        segLastIndex = pattern.lastIndex;
      }
      if (segLastIndex < plainText.length) {
        container.appendChild(document.createTextNode(plainText.substring(segLastIndex)));
      }
    };

    while ((match = wikiLinkRegex.exec(text)) !== null) {
      if (match.index > lastIndex) {
        processPlainSegment(text.substring(lastIndex, match.index));
      }
      let target, display;
      if (match[1] !== void 0) {
        target = match[1];
        display = match[2] || match[1];
      } else {
        display = match[3];
        target = match[4];
      }
      let a = container.createEl("a", {
        text: display,
        cls: "internal-link",
        attr: { "data-href": target, href: target }
      });
      a.addEventListener("click", (evt) => {
        evt.preventDefault();
        this.app.workspace.openLinkText(target, "", evt.metaKey || evt.ctrlKey);
      });
      lastIndex = wikiLinkRegex.lastIndex;
    }
    if (lastIndex < text.length) {
      processPlainSegment(text.substring(lastIndex));
    }
  }

  async onload() {
    await this.loadSettings();
    this.applyCSSVars();
    this.addSettingTab(new E(this.app, this));
    this.registerMarkdownCodeBlockProcessor("tree", this.treeProcessor);
    this.addCommand({
      id: "convert-to-tree-block",
      name: "Convert selection to tree code block",
      editorCallback: (e) => { this.convertSelectionToTreeBlock(e); }
    });
    this.addCommand({
      id: "remove-tree-block",
      name: "Convert tree block back to text",
      editorCallback: (e) => { this.removeTreeBlock(e); }
    });
    this.addCommand({
      id: "toggle-tree-block",
      name: "Toggle tree block",
      editorCallback: (e) => { this.toggleTreeBlock(e); }
    });
  }

  async loadSettings() {
    this.settings = Object.assign({}, W, await this.loadData());
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }

  convertSelectionToTreeBlock(e) {
    let s = e.getSelection();
    if (s) {
      e.replaceSelection("```tree\n" + s + "\n```");
    } else {
      let o = e.getCursor().line,
        a = e.getLine(o),
        r = { line: o, ch: 0 },
        t = { line: o, ch: a.length };
      e.replaceRange("```tree\n" + a + "\n```", r, t);
      e.setCursor(o + 1, a.length);
    }
  }

  removeTreeBlock(e) {
    let s = e.getCursor(),
      o = e.getValue().split("\n"),
      a = s.line,
      i = -1,
      r = -1;
    for (let t = a; t >= 0; t--) {
      if (o[t].trim().match(/^```tree\s*$/)) { i = t; break; }
      if (t !== a && o[t].trim().match(/^```/)) break;
    }
    if (i !== -1)
      for (let t = i + 1; t < o.length; t++)
        if (o[t].trim() === "```") { r = t; break; }
    if (i !== -1 && r !== -1 && a >= i && a <= r) {
      let t = o.slice(i + 1, r).join("\n"),
        S = { line: i, ch: 0 },
        w = { line: r, ch: o[r].length };
      e.replaceRange(t, S, w);
      e.setCursor(i, 0);
    }
  }

  toggleTreeBlock(e) {
    this.isInsideTreeBlock(e) ? this.removeTreeBlock(e) : this.convertSelectionToTreeBlock(e);
  }

  isInsideTreeBlock(e) {
    let s = e.getCursor(),
      o = e.getValue().split("\n"),
      a = s.line,
      i = -1,
      r = -1;
    for (let t = a; t >= 0; t--) {
      if (o[t].trim().match(/^```tree\s*$/)) { i = t; break; }
      if (t !== a && o[t].trim().match(/^```/)) break;
    }
    if (i !== -1)
      for (let t = i + 1; t < o.length; t++)
        if (o[t].trim() === "```") { r = t; break; }
    return i !== -1 && r !== -1 && a >= i && a <= r;
  }
};

/* ── Settings Tab ──────────────────────────────────────────────── */
var E = class extends u.PluginSettingTab {
  constructor(e, s) {
    super(e, s);
    this.plugin = s;
  }

  display() {
    let { containerEl: e } = this;
    e.empty();
    let T = (key) => this.plugin.t(key);

    /* ── Language selector — always first ─────────────────── */
    new u.Setting(e)
      .setName(T("langSettingName"))
      .setDesc(T("langSettingDesc"))
      .addDropdown((s) =>
        s
          .addOption("es", T("langEs"))
          .addOption("en", T("langEn"))
          .setValue(this.plugin.settings.language || "es")
          .onChange(async (l) => {
            this.plugin.settings.language = l;
            await this.plugin.saveSettings();
            // Refresh settings panel immediately with new language
            this.display();
          })
      );

    /* ── Section: Tree Appearance ─────────────────────────── */
    e.createEl("h3", { text: T("sectionAppearance") });

    new u.Setting(e)
      .setName(T("treeStyleName"))
      .setDesc(T("treeStyleDesc"))
      .addDropdown((s) =>
        s
          .addOption("classic",   T("styleClassic"))
          .addOption("rounded",   T("styleRounded"))
          .addOption("heavy",     T("styleHeavy"))
          .addOption("double",    T("styleDouble"))
          .addOption("dotted",    T("styleDotted"))
          .addOption("slim",      T("styleSlim"))
          .addOption("asciiplus", T("styleAsciiplus"))
          .addOption("arrows",    T("styleArrows"))
          .setValue(this.plugin.settings.treeStyle || "classic")
          .onChange(async (l) => {
            this.plugin.settings.treeStyle = l;
            await this.plugin.saveSettings();
            this.plugin.rerenderAllBlocks();
          })
      );

    new u.Setting(e)
      .setName(T("dashCountName"))
      .setDesc(T("dashCountDesc"))
      .addSlider((s) =>
        s
          .setLimits(1, 10, 1)
          .setValue(this.plugin.settings.dashCount)
          .setDynamicTooltip()
          .onChange(async (l) => {
            this.plugin.settings.dashCount = l;
            await this.plugin.saveSettings();
            this.plugin.rerenderAllBlocks();
          })
      );

    new u.Setting(e)
      .setName(T("autoSlashName"))
      .setDesc(T("autoSlashDesc"))
      .addToggle((s) =>
        s.setValue(this.plugin.settings.autoAppendSlash).onChange(async (l) => {
          this.plugin.settings.autoAppendSlash = l;
          await this.plugin.saveSettings();
          this.plugin.rerenderAllBlocks();
        })
      );

    /* ── Section: Title Line ──────────────────────────────── */
    e.createEl("h3", { text: T("sectionTitle") });

    new u.Setting(e)
      .setName(T("titleFormatName"))
      .setDesc(T("titleFormatDesc"))
      .addToggle((s) =>
        s.setValue(this.plugin.settings.enableTitleFormat).onChange(async (l) => {
          this.plugin.settings.enableTitleFormat = l;
          await this.plugin.saveSettings();
          this.plugin.rerenderAllBlocks();
        })
      );

    new u.Setting(e)
      .setName(T("titleSpacingName"))
      .setDesc(T("titleSpacingDesc"))
      .addSlider((s) =>
        s
          .setLimits(0, 40, 1)
          .setValue(this.plugin.settings.titleSpacing ?? 12)
          .setDynamicTooltip()
          .onChange(async (l) => {
            this.plugin.settings.titleSpacing = l;
            await this.plugin.saveSettings();
            this.plugin.applyCSSVars();
          })
      );

    /* ── Section: Link Hover ──────────────────────────────── */
    e.createEl("h3", { text: T("sectionHover") });

    new u.Setting(e)
      .setName(T("hoverEnableName"))
      .setDesc(T("hoverEnableDesc"))
      .addToggle((s) =>
        s.setValue(this.plugin.settings.enableLinkHover).onChange(async (l) => {
          this.plugin.settings.enableLinkHover = l;
          await this.plugin.saveSettings();
          this.plugin.updateHoverClasses();
        })
      );

    new u.Setting(e)
      .setName(T("hoverStyleName"))
      .setDesc(T("hoverStyleDesc"))
      .addDropdown((s) =>
        s
          .addOption("bold",      T("hoverBold"))
          .addOption("border",    T("hoverBorder"))
          .addOption("underline", T("hoverUnderline"))
          .addOption("highlight", T("hoverHighlight"))
          .addOption("glow",      T("hoverGlow"))
          .addOption("pill",      T("hoverPill"))
          .addOption("neon",      T("hoverNeon"))
          .addOption("ghost",     T("hoverGhost"))
          .addOption("boldglow",  T("hoverBoldglow"))
          .setValue(this.plugin.settings.linkHoverStyle || "bold")
          .onChange(async (l) => {
            this.plugin.settings.linkHoverStyle = l;
            await this.plugin.saveSettings();
            this.plugin.updateHoverClasses();
          })
      );
  }
};

/* nosourcemap */