/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin: https://github.com/Baalgarthem
*/

/* ========================================================================
   SECTION 1: IMPORTS & CORE MODULE EXPORTS
   ======================================================================== */
var L = Object.defineProperty;
var I = Object.getOwnPropertyDescriptor;
var $ = Object.getOwnPropertyNames;
var P = Object.prototype.hasOwnProperty;
var V = (p, h) => {
  for (var e in h) L(p, e, { get: h[e], enumerable: !0 });
};
var j = (p, h, e, s) => {
  if ((h && typeof h == "object") || typeof h == "function")
    for (let l of $(h))
      !P.call(p, l) &&
        l !== e &&
        L(p, l, { get: () => h[l], enumerable: !(s = I(h, l)) || s.enumerable });
  return p;
};
var D = (p) => j(L({}, "__esModule", { value: !0 }), p);
var N = {};
V(N, { default: () => b });
module.exports = D(N);

var u = require("obsidian");

/* ========================================================================
   SECTION 2: INTERNATIONALIZATION (TRANSLATIONS & DICTIONARIES)
   ======================================================================== */
var TRANSLATIONS = {
  es: {
    // Language setting
    langSettingName: "Idioma / Language",
    langSettingDesc: "Idioma de la interfaz de configuración.",
    langEs: "Español",
    langEn: "English",

    // Information section
    sectionBlockTypes: "Tipos de Bloques Disponibles",
    blockTypesDesc: "Todos los tipos de diagramas están habilitados por defecto. Puedes declararlos directamente en tus notas usando las cercas de código correspondientes:",
    infoTree:  "```tree — Árbol por defecto (lista con conectores ├── y └──)",
    infoTreeV: "```tree-v — Organigrama vertical Top-Down (diagrama en cajas centradas)",
    infoTreeK: "```tree-k — Cuadro sinóptico (diagrama por llaves centradas)",
    ghostTreeNotice: "✦ Nota pedagogica: La etiqueta ```tree genera siempre un árbol ASCII de lista tradicional por defecto. Para utilizar diagramas alternativos, debes declararlos explícitamente como ```tree-v o ```tree-k.",
    emptyBlockPlaceholder: "✦ Ingresa un título o elementos para generar el diagrama...",

    // Sections
    sectionAppearance: "Apariencia del Árbol",
    sectionTitle:      "Línea de Título",
    sectionHover:      "Efectos al Pasar el Cursor",

    // Tree style
    treeStyleName: "Estilo de ramas",
    treeStyleDesc: "Elige el estilo visual de los conectores del árbol. Los cambios se aplican de inmediato.",
    styleClassic:   "Clásico      (├──, └──, │)",
    styleRounded:   "Redondeado   (├──, ╰──, │)",
    styleHeavy:     "Grueso       (┣━━, ┗━━, ┃)",
    styleDouble:    "Doble Línea  (╠══, ╚══, ║)",
    styleDotted:    "Punteado     (├──, └──, ┊)",
    styleSlim:      "Fino Dashed  (├╌╌, └╌╌, ╎)",
    styleAsciiplus: "ASCII Plus   (+--,  +--,  |)",
    styleArrows:    "Flechas      (╞══, ╘══, │)",

    // Connector dashes
    dashCountName: "Número de guiones",
    dashCountDesc: "Cuántos caracteres de guión siguen a cada símbolo de rama.",

    // Auto-slash
    autoSlashName: "Añadir / a carpetas",
    autoSlashDesc: "Agrega una barra diagonal a los elementos que tienen hijos.",

    // Title format
    titleFormatName:   "Formatear primera línea como título",
    titleFormatDesc:   "Aplica mayor tamaño de fuente y espaciado configurable a la primera línea del bloque.",
    titleSpacingName:  "Espaciado inferior del título (px)",
    titleSpacingDesc:  "Espacio entre la línea de título y el primer elemento del árbol. 0 = casi juntos.",

    // Hover
    hoverEnableName:  "Activar efecto al pasar el cursor",
    hoverEnableDesc:  "Resalta enlaces nativos de Obsidian y de Virtual Linker al pasar el cursor.",
    hoverStyleName:   "Estilo del hover",
    hoverStyleDesc:   "Efecto visual aplicado a los enlaces al pasar el cursor. Cambios inmediatos.",
    hoverBold:      "✦ Negrita — texto en negrita",
    hoverBorder:    "⬜ Borde — recuadro de contorno",
    hoverUnderline: "― Subrayado — subrayado animado",
    hoverHighlight: "🖊 Marcador — fondo de marcador de texto",
    hoverGlow:      "✦ Iluminación — resplandor suave",
    hoverPill:      "💊 Pastilla — fondo de color sólido",
    hoverNeon:      "⚡ Neón — brillo neón",
    hoverGhost:     "👻 Fantasma — marco punteado sutil",
    hoverBoldglow:  "✨ Negrita + Brillo — combinado",
  },
  en: {
    // Language setting
    langSettingName: "Idioma / Language",
    langSettingDesc: "Settings interface language.",
    langEs: "Español",
    langEn: "English",

    // Information section
    sectionBlockTypes: "Available Diagram Block Types",
    blockTypesDesc: "All diagram block types are enabled by default. Declare them directly in your notes using these code block tags:",
    infoTree:  "```tree — Default tree (list with ├── and └── connectors)",
    infoTreeV: "```tree-v — Vertical Top-Down Organigram (centered box chart)",
    infoTreeK: "```tree-k — Synoptic Diagram (centered key brace chart)",
    ghostTreeNotice: "✦ Notice: The ```tree tag always renders a traditional list ASCII tree by default. For alternative diagrams, explicitly declare ```tree-v or ```tree-k.",
    emptyBlockPlaceholder: "✦ Enter a title or tree elements to generate diagram...",

    // Sections
    sectionAppearance: "Tree Appearance",
    sectionTitle:      "Title Line",
    sectionHover:      "Link Hover Effects",

    // Tree style
    treeStyleName: "Tree branch style",
    treeStyleDesc: "Choose the visual style for branch connectors. Changes apply immediately to all rendered trees.",
    styleClassic:   "Classic      (├──, └──, │)",
    styleRounded:   "Rounded      (├──, ╰──, │)",
    styleHeavy:     "Heavy        (┣━━, ┗━━, ┃)",
    styleDouble:    "Double Line  (╠══, ╚══, ║)",
    styleDotted:    "Dotted Stem  (├──, └──, ┊)",
    styleSlim:      "Slim Dashed  (├╌╌, └╌╌, ╎)",
    styleAsciiplus: "ASCII Plus   (+--,  +--,  |)",
    styleArrows:    "Arrows       (╞══, ╘══, │)",

    // Connector dashes
    dashCountName: "Connector dashes",
    dashCountDesc: "Sets how many dash/connector characters follow each branch symbol.",

    // Auto-slash
    autoSlashName: "Auto-append / to folders",
    autoSlashDesc: "Automatically add a trailing slash to items that have children.",

    // Title format
    titleFormatName:  "Format first line as title",
    titleFormatDesc:  "Style the first line with larger text and configurable bottom spacing.",
    titleSpacingName: "Title bottom spacing (px)",
    titleSpacingDesc: "Space between the title line and the first tree element. 0 = almost touching.",

    // Hover
    hoverEnableName:  "Enable link hover effect",
    hoverEnableDesc:  "Highlight native Obsidian links and Virtual Linker links on mouse hover.",
    hoverStyleName:   "Link hover style",
    hoverStyleDesc:   "Visual effect applied to links on mouse hover. Changes apply instantly.",
    hoverBold:      "✦ Bold — bold text",
    hoverBorder:    "⬜ Border — outline box",
    hoverUnderline: "― Underline — animated underline",
    hoverHighlight: "🖊 Highlight — text marker background",
    hoverGlow:      "✦ Glow — soft glow",
    hoverPill:      "💊 Pill — solid color background",
    hoverNeon:      "⚡ Neon — neon glow",
    hoverGhost:     "👻 Ghost — subtle dashed frame",
    hoverBoldglow:  "✨ Bold + Glow — combined",
  }
};

/* ========================================================================
   SECTION 3: DIAGRAM SYMBOL DEFINITIONS & VISUAL PRESETS
   - STYLES: Default Classic List Tree Branch Connectors
   - ORGANIGRAM_SYMBOLS: Vertical Top-Down Organigram Symbols (tree-v)
   - SYNOPTIC_SYMBOLS: Horizontal Synoptic Key Symbols (tree-k)
   ======================================================================== */
var STYLES = {
  classic:   { branch: "├", last: "└", dash: "─", stem: "│" },
  rounded:   { branch: "├", last: "╰", dash: "─", stem: "│" },
  heavy:     { branch: "┣", last: "┗", dash: "━", stem: "┃" },
  double:    { branch: "╠", last: "╚", dash: "═", stem: "║" },
  dotted:    { branch: "├", last: "└", dash: "─", stem: "┊" },
  slim:      { branch: "├", last: "└", dash: "╌", stem: "╎" },
  asciiplus: { branch: "+", last: "+", dash: "-", stem: "|" },
  arrows:    { branch: "╞", last: "╘", dash: "═", stem: "│" }
};

var ORGANIGRAM_SYMBOLS = {
  classic:   { dash: "─", stem: "│", topCorner: "┌", topRightCorner: "┐", topT: "┬", bottomT: "┴", cross: "┼" },
  rounded:   { dash: "─", stem: "│", topCorner: "╭", topRightCorner: "╮", topT: "┬", bottomT: "┴", cross: "┼" },
  heavy:     { dash: "━", stem: "┃", topCorner: "┏", topRightCorner: "┓", topT: "┳", bottomT: "┻", cross: "╋" },
  double:    { dash: "═", stem: "║", topCorner: "╔", topRightCorner: "╗", topT: "╦", bottomT: "╩", cross: "╬" },
  dotted:    { dash: "─", stem: "┊", topCorner: "┌", topRightCorner: "┐", topT: "┬", bottomT: "┴", cross: "┼" },
  slim:      { dash: "╌", stem: "╎", topCorner: "┌", topRightCorner: "┐", topT: "┬", bottomT: "┴", cross: "┼" },
  asciiplus: { dash: "-", stem: "|", topCorner: "+", topRightCorner: "+", topT: "+", bottomT: "+", cross: "+" },
  arrows:    { dash: "═", stem: "│", topCorner: "┌", topRightCorner: "┐", topT: "╦", bottomT: "╩", cross: "╬" }
};

var SYNOPTIC_SYMBOLS = {
  classic:   { dash: "─", stem: "│", topCorner: "┌", bottomCorner: "└", cusp: "├" },
  rounded:   { dash: "─", stem: "│", topCorner: "╭", bottomCorner: "╰", cusp: "├" },
  heavy:     { dash: "━", stem: "┃", topCorner: "┏", bottomCorner: "┗", cusp: "┣" },
  double:    { dash: "═", stem: "║", topCorner: "╔", bottomCorner: "╚", cusp: "╠" },
  dotted:    { dash: "─", stem: "┊", topCorner: "┌", bottomCorner: "└", cusp: "├" },
  slim:      { dash: "╌", stem: "╎", topCorner: "┌", bottomCorner: "└", cusp: "├" },
  asciiplus: { dash: "-", stem: "|", topCorner: "+", bottomCorner: "+", cusp: "+" },
  arrows:    { dash: "═", stem: "│", topCorner: "┌", bottomCorner: "└", cusp: "╞" }
};

/* ========================================================================
   SECTION 4: DEFAULT PLUGIN CONFIGURATION SCHEMA (W)
   ======================================================================== */
var W = {
  language: "es",
  enableTreeV: !0,
  centerTreeV: !0,
  enableTreeK: !0,
  centerTreeK: !0,
  dashCount: 2,
  autoAppendSlash: !1,
  treeStyle: "classic",
  enableLinkHover: !0,
  linkHoverStyle: "bold",
  enableTitleFormat: !0,
  titleFontSize: "1.15em",
  titleSpacing: 12
};

/* ========================================================================
   SECTION 5: MAIN PLUGIN CLASS ENGINE (ASCII Tree Generator Extended)
   ======================================================================== */
var b = class extends u.Plugin {
  /* ── 5.1 Constructor & Internal State Initialization ── */
  constructor() {
    super(...arguments);
    this.renderedBlocks = new Map();
    this._cachedNoteMapInfo = null;

    this.treeProcessor = (sourceText, containerEl, ctx, mode = null) => {
      this.renderedBlocks.set(containerEl, { sourceText, mode });
      if (ctx && ctx.addChild) {
        let comp = new u.Component();
        comp.onunload = () => {
          this.renderedBlocks.delete(containerEl);
        };
        ctx.addChild(comp);
      }
      this._renderTree(sourceText, containerEl, ctx, mode);
    };
  }

  /* ── 5.2 Translation & Vault Cache Helper Methods ── */
  t(key) {
    let lang = this.settings.language || "es";
    let dict = TRANSLATIONS[lang] || TRANSLATIONS.es;
    return dict[key] || TRANSLATIONS.es[key] || key;
  }

  /* ── 5.3 Core Dispatcher & Routing Engine ── */
  _renderTree(sourceText, containerEl, ctx, modeOverride = null) {
    let a = this.settings.dashCount;

    if (modeOverride === "v") {
      return this._renderTreeV(sourceText, containerEl, ctx, a);
    }
    if (modeOverride === "k") {
      return this._renderTreeK(sourceText, containerEl, ctx, a);
    }

    return this._renderTreeClassic(sourceText, containerEl, ctx, a);
  }

  /* ── 5.4 Empty Block Placeholder Engine ── */
  _renderEmptyBlockPlaceholder(containerEl, mode = null) {
    containerEl.empty();
    let preEl = containerEl.createEl("pre");
    preEl.addClass("ascii-tree-block");
    preEl.addClass("ascii-tree-empty");
    if (mode === "v") {
      preEl.addClass("ascii-tree-v");
      if (this.settings.centerTreeV) preEl.addClass("ascii-tree-center");
    } else if (mode === "k") {
      preEl.addClass("ascii-tree-k");
      if (this.settings.centerTreeK) preEl.addClass("ascii-tree-center");
    }

    let codeEl = preEl.createEl("code");
    let sp = codeEl.createEl("span", { cls: "ascii-tree-ghost-placeholder" });
    sp.innerText = this.t("emptyBlockPlaceholder");
  }

  /* ── 5.5 Render Engine A: Classic List Tree (tree) ── */
  _renderTreeClassic(sourceText, containerEl, ctx, dashCount) {
    try {
      let { autoAppendSlash: o } = this.settings;
      let a = dashCount ?? this.settings.dashCount;
      let styleKey = this.settings.treeStyle || "classic";
      let sym = STYLES[styleKey] || STYLES.classic;

      let r = sym.dash.repeat(a),
        t = sym.branch + r + " ",
        S = sym.last + r + " ",
        w = sym.stem + " ".repeat(a + 1),
        A = " ".repeat(a + 2),
        T = sourceText.split("\n"),
        v = 1 / 0;

      for (let n of T)
        if (n.trim() !== "") {
          let c = n.match(/^([\t ]*)/);
          c && c[1].length < v && (v = c[1].length);
        }

      let C = "";
      v !== 1 / 0 &&
        v > 0 &&
        (C = ((B = T.find((n) => n.trim() !== "")) == null ? void 0 : B.slice(0, v)) || "");

      let m = T.map((n) => (n.startsWith(C) ? n.slice(C.length) : n)).map((n) => {
        let c = n.match(/^([\t ]*)((?:[-*+─—–‒•⁃])|\d+\.)\s*(.*)$/);
        if (c) {
          let f = c[1],
            k = (f.match(/\t/g) || []).length,
            d = (f.match(/ /g) || []).length,
            x = k + Math.floor(d / 4);
          return x++, { level: x, leadingWhitespace: "", text: c[3] ? c[3].trim() : "" };
        }
        let g = n.match(/^(=+)\s?(.*)$/);
        return g
          ? { level: g[1].length, leadingWhitespace: "", text: g[2] ? g[2].trim() : "" }
          : { level: 0, leadingWhitespace: "", text: n ? n.trim() : "" };
      }).filter((n) => n.text !== "");

      if (m.length === 0) {
        return this._renderEmptyBlockPlaceholder(containerEl, null);
      }

      let y = [];
      let M = m
        .map((n, c) => {
          let g = !0;
          for (let d = c + 1; d < m.length && !(m[d].level < n.level); d++)
            if (m[d].level === n.level) { g = !1; break; }
          y[n.level] = g;
          y.length = n.level + 1;
          let f = "";
          for (let d = 1; d < n.level; d++) f += y[d] ? A : w;
          n.level > 0 && (f += g ? S : t);
          let k = n.text;
          o &&
            n.level > 0 &&
            c + 1 < m.length &&
            m[c + 1].level > n.level &&
            !k.endsWith("/") &&
            (k += "/");
          return `${C}${n.leadingWhitespace}${f}${k}`;
        })
        .join("\n");

      containerEl.empty();
      let preEl = containerEl.createEl("pre");
      preEl.addClass("ascii-tree-block");

      if (this.settings.enableLinkHover) {
        preEl.addClass("ascii-tree-hover-" + (this.settings.linkHoverStyle || "bold"));
      }

      let codeEl = preEl.createEl("code");
      let noteMapInfo = this.getVaultNoteMapInfo();
      let ls = M.split("\n");
      let frag = document.createDocumentFragment();

      for (let j = 0; j < ls.length; j++) {
        let sp = document.createElement("span");
        let lineText = ls[j];

        if (j === 0 && this.settings.enableTitleFormat) {
          sp.addClass("ascii-tree-title");
          sp.setAttribute("data-spacing", String(this.settings.titleSpacing ?? 12));
          sp.style.fontSize = "var(--ascii-tree-title-font-size, " + (this.settings.titleFontSize || "1.15em") + ")";
          sp.style.marginBottom = "var(--ascii-tree-title-margin-bottom, 12px)";
        }

        this.renderLineContent(sp, lineText, noteMapInfo);

        frag.appendChild(sp);
        if (j < ls.length - 1) {
          frag.appendChild(document.createTextNode("\n"));
        }
      }
      codeEl.appendChild(frag);
    } catch (err) {
      console.error("[ASCII Tree EX] Safe classic render caught exception:", err);
    }
  }

  /* ── 5.6 Helper Utilities: Matrix Grid & Text Formatting ── */
  getVisibleTextLength(text) {
    if (!text) return 0;
    let cleaned = text
      .replace(/\[\[([^\]\|]+)\|([^\]]+)\]\]/g, "$2")
      .replace(/\[\[([^\]]+)\]\]/g, "$1")
      .replace(/\[([^\]]+)\]\([^\)]+\)/g, "$1");
    return cleaned.length;
  }

  safeSetGrid(grid, r, c, val, maxColX) {
    if (r >= 0 && r < grid.length && Array.isArray(grid[r]) && c >= 0 && c < maxColX) {
      grid[r][c] = val;
    }
  }

  safeGetGrid(grid, r, c, maxColX) {
    if (r >= 0 && r < grid.length && Array.isArray(grid[r]) && c >= 0 && c < maxColX) {
      return grid[r][c];
    }
    return null;
  }

  wrapText(text, maxLineLen = 24) {
    if (!text) return [""];
    let cleaned = text
      .replace(/\[\[([^\]\|]+)\|([^\]]+)\]\]/g, "$2")
      .replace(/\[\[([^\]]+)\]\]/g, "$1")
      .replace(/\[([^\]]+)\]\([^\)]+\)/g, "$1");
    if (cleaned.length <= maxLineLen) return [text];

    let words = text.split(" ");
    let lines = [];
    let curLine = "";

    for (let word of words) {
      let testLine = curLine ? curLine + " " + word : word;
      let testClean = testLine
        .replace(/\[\[([^\]\|]+)\|([^\]]+)\]\]/g, "$2")
        .replace(/\[\[([^\]]+)\]\]/g, "$1")
        .replace(/\[([^\]]+)\]\([^\)]+\)/g, "$1");

      if (testClean.length <= maxLineLen || !curLine) {
        curLine = testLine;
      } else {
        lines.push(curLine);
        curLine = word;
      }
    }
    if (curLine) lines.push(curLine);
    return lines;
  }

  /* ── 5.7 Render Engine B: Vertical Top-Down Organigram (tree-v) ── */
  _renderTreeV(sourceText, containerEl, ctx, dashCount) {
    try {
      let { autoAppendSlash: o } = this.settings;
      let styleKey = this.settings.treeStyle || "classic";
      let symH = ORGANIGRAM_SYMBOLS[styleKey] || ORGANIGRAM_SYMBOLS.classic;

      let T = sourceText.split("\n");
      let v = 1 / 0;

      for (let n of T)
        if (n.trim() !== "") {
          let c = n.match(/^([\t ]*)/);
          c && c[1].length < v && (v = c[1].length);
        }

      let C = "";
      v !== 1 / 0 &&
        v > 0 &&
        (C = (T.find((n) => n.trim() !== "")?.slice(0, v)) || "");

      let m = T.map((n) => (n.startsWith(C) ? n.slice(C.length) : n)).map((n) => {
        let c = n.match(/^([\t ]*)((?:[-*+─—–‒•⁃])|\d+\.)\s*(.*)$/);
        if (c) {
          let f = c[1],
            k = (f.match(/\t/g) || []).length,
            d = (f.match(/ /g) || []).length,
            x = k + Math.floor(d / 4);
          return x++, { level: x, text: c[3] ? c[3].trim() : "" };
        }
        let g = n.match(/^(=+)\s?(.*)$/);
        return g
          ? { level: g[1].length, text: g[2] ? g[2].trim() : "" }
          : { level: 0, text: n ? n.trim() : "" };
      });

      let items = m.filter((n) => n.text !== "");
      if (items.length === 0) {
        return this._renderEmptyBlockPlaceholder(containerEl, "v");
      }

      let nodes = items.map((it, idx) => {
        let lines = this.wrapText(it.text, 24);
        let visLen = Math.max(...lines.map((l) => this.getVisibleTextLength(l)));
        return {
          id: idx,
          level: it.level,
          text: it.text,
          lines: lines,
          visLen: visLen,
          children: [],
          parent: null,
          depth: 0,
          startX: 0,
          centerX: 0,
          subtreeWidth: 0
        };
      });

      let stack = [];
      for (let node of nodes) {
        while (stack.length > 0 && stack[stack.length - 1].level >= node.level) {
          stack.pop();
        }
        if (stack.length > 0) {
          let parentNode = stack[stack.length - 1];
          parentNode.children.push(node);
          node.parent = parentNode;
        }
        stack.push(node);
      }

      let roots = nodes.filter((n) => n.parent === null);

      let setDepth = (node, d) => {
        node.depth = d;
        for (let c of node.children) {
          setDepth(c, d + 1);
        }
      };
      for (let root of roots) {
        setDepth(root, 0);
      }

      if (o) {
        for (let node of nodes) {
          if (node.children.length > 0) {
            let lastLineIdx = node.lines.length - 1;
            if (!node.lines[lastLineIdx].endsWith("/")) {
              node.lines[lastLineIdx] += "/";
              node.visLen = Math.max(...node.lines.map((l) => this.getVisibleTextLength(l)));
            }
          }
        }
      }

      let gap = Math.max(3, dashCount * 2 + 1);

      // 1. Calculate subtreeWidth for each node bottom-up
      let calcSubtreeWidth = (node) => {
        if (node.children.length === 0) {
          node.subtreeWidth = node.visLen;
        } else {
          let sumChildrenWidth = 0;
          for (let i = 0; i < node.children.length; i++) {
            calcSubtreeWidth(node.children[i]);
            sumChildrenWidth += node.children[i].subtreeWidth;
          }
          sumChildrenWidth += (node.children.length - 1) * gap;
          node.subtreeWidth = Math.max(node.visLen, sumChildrenWidth);
        }
      };
      for (let root of roots) {
        calcSubtreeWidth(root);
      }

      // 2. Assign positions top-down with smart balanced child spacing
      let assignPositions = (node, leftBound) => {
        node.startX = leftBound + Math.floor((node.subtreeWidth - node.visLen) / 2);
        node.centerX = node.startX + Math.floor(node.visLen / 2);

        if (node.children.length === 1) {
          let child = node.children[0];
          let childLeft = leftBound + Math.floor((node.subtreeWidth - child.subtreeWidth) / 2);
          assignPositions(child, childLeft);
          if (child.subtreeWidth <= node.subtreeWidth) {
            node.centerX = child.centerX;
            node.startX = node.centerX - Math.floor(node.visLen / 2);
          }
        } else if (node.children.length > 1) {
          let sumChildWidths = node.children.reduce((acc, c) => acc + c.subtreeWidth, 0);
          let remSpace = node.subtreeWidth - sumChildWidths;
          let numGaps = node.children.length - 1;
          let smartGap = Math.max(gap, Math.floor(remSpace / numGaps));
          let remMargin = remSpace - smartGap * numGaps;
          let childLeft = leftBound + Math.floor(remMargin / 2);

          for (let child of node.children) {
            assignPositions(child, childLeft);
            childLeft += child.subtreeWidth + smartGap;
          }
          let firstChild = node.children[0];
          let lastChild = node.children[node.children.length - 1];
          let childrenMidX = Math.floor((firstChild.centerX + lastChild.centerX) / 2);
          node.centerX = childrenMidX;
          node.startX = node.centerX - Math.floor(node.visLen / 2);
        }
      };

      let currentRootLeft = 0;
      for (let root of roots) {
        assignPositions(root, currentRootLeft);
        currentRootLeft += root.subtreeWidth + gap * 2;
      }

      // Ensure all node coordinates are non-negative
      let minStartX = Math.min(...nodes.map((n) => n.centerX - Math.floor(n.visLen / 2)));
      if (minStartX < 0) {
        let shiftX = -minStartX;
        for (let n of nodes) {
          n.startX += shiftX;
          n.centerX += shiftX;
        }
      }

      let maxDepth = Math.max(...nodes.map((n) => n.depth));
      let maxLinesByDepth = new Map();
      for (let d = 0; d <= maxDepth; d++) {
        let dNodes = nodes.filter((n) => n.depth === d);
        let maxL = dNodes.length > 0 ? Math.max(...dNodes.map((n) => n.lines.length)) : 1;
        maxLinesByDepth.set(d, maxL);
      }

      let depthStartY = new Map();
      let curY = 0;
      for (let d = 0; d <= maxDepth; d++) {
        depthStartY.set(d, curY);
        curY += (maxLinesByDepth.get(d) || 1) + 2;
      }

      let totalRows = Math.min(curY + 2, 500);
      let calculatedMaxX = Math.max(...nodes.map((n) => n.centerX + Math.ceil(n.visLen / 2))) + 10;
      let maxColX = Math.min(Math.max(calculatedMaxX, 20), 2000);

      let grid = Array.from({ length: totalRows }, () => Array(maxColX + 2).fill(" "));

      // 1. Draw node text lines directly into grid
      for (let node of nodes) {
        let d = node.depth;
        let pY = depthStartY.get(d) || 0;
        for (let lIdx = 0; lIdx < node.lines.length; lIdx++) {
          let lineText = node.lines[lIdx];
          let lineVisLen = this.getVisibleTextLength(lineText);
          let startX = Math.max(0, node.centerX - Math.floor(lineVisLen / 2));
          for (let k = 0; k < lineText.length; k++) {
            this.safeSetGrid(grid, pY + lIdx, startX + k, lineText[k], maxColX);
          }
        }
      }

      // 2. Draw connector branches (only over empty space)
      for (let node of nodes) {
        if (node.children.length > 0) {
          let d = node.depth;
          let pY = depthStartY.get(d) || 0;
          let mL = maxLinesByDepth.get(d) || 1;

          let pX = Math.min(Math.max(0, node.centerX), maxColX - 1);
          let dropRow = pY + mL;
          let barRow = pY + mL + 1;

          let firstChild = node.children[0];
          let lastChild = node.children[node.children.length - 1];
          let leftX = Math.min(Math.max(0, firstChild.centerX), maxColX - 1);
          let rightX = Math.min(Math.max(0, lastChild.centerX), maxColX - 1);

          if (barRow < totalRows) {
            if (node.children.length === 1) {
              let lineX = pX;
              if (dropRow < totalRows && this.safeGetGrid(grid, dropRow, lineX, maxColX) === " ") {
                this.safeSetGrid(grid, dropRow, lineX, symH.stem, maxColX);
              }
              if (this.safeGetGrid(grid, barRow, lineX, maxColX) === " ") {
                this.safeSetGrid(grid, barRow, lineX, symH.stem, maxColX);
              }
            } else {
              if (dropRow < totalRows && this.safeGetGrid(grid, dropRow, pX, maxColX) === " ") {
                this.safeSetGrid(grid, dropRow, pX, symH.stem, maxColX);
              }
              for (let x = leftX; x <= rightX; x++) {
                if (x < maxColX && this.safeGetGrid(grid, barRow, x, maxColX) === " ") {
                  this.safeSetGrid(grid, barRow, x, symH.dash, maxColX);
                }
              }
              if (leftX < maxColX && this.safeGetGrid(grid, barRow, leftX, maxColX) === symH.dash) {
                this.safeSetGrid(grid, barRow, leftX, symH.topCorner, maxColX);
              }
              if (rightX < maxColX && this.safeGetGrid(grid, barRow, rightX, maxColX) === symH.dash) {
                this.safeSetGrid(grid, barRow, rightX, symH.topRightCorner, maxColX);
              }

              for (let i = 1; i < node.children.length - 1; i++) {
                let childX = Math.min(Math.max(0, node.children[i].centerX), maxColX - 1);
                if (childX < maxColX && this.safeGetGrid(grid, barRow, childX, maxColX) === symH.dash) {
                  this.safeSetGrid(grid, barRow, childX, symH.topT, maxColX);
                }
              }

              let isChildX = node.children.some((c) => c.centerX === pX);
              if (pX === leftX) {
                if (pX < maxColX) this.safeSetGrid(grid, barRow, pX, symH.topCorner, maxColX);
              } else if (pX === rightX) {
                if (pX < maxColX) this.safeSetGrid(grid, barRow, pX, symH.topRightCorner, maxColX);
              } else {
                if (pX < maxColX) this.safeSetGrid(grid, barRow, pX, isChildX ? symH.cross : symH.bottomT, maxColX);
              }
            }
          }
        }
      }

      let linesOutput = [];
      for (let r = 0; r < totalRows; r++) {
        let lineStr = grid[r].join("").replace(/\s+$/, "");
        linesOutput.push(lineStr);
      }

      while (linesOutput.length > 0 && linesOutput[linesOutput.length - 1] === "") {
        linesOutput.pop();
      }

      if (linesOutput.length === 0) {
        return this._renderEmptyBlockPlaceholder(containerEl, "v");
      }

      containerEl.empty();
      let preEl = containerEl.createEl("pre");
      preEl.addClass("ascii-tree-block");
      preEl.addClass("ascii-tree-v");
      if (this.settings.centerTreeV) {
        preEl.addClass("ascii-tree-center");
      }

            if (this.settings.enableLinkHover) {
        preEl.addClass("ascii-tree-hover-" + (this.settings.linkHoverStyle || "bold"));
      }

      let codeEl = preEl.createEl("code");
      let noteMapInfo = this.getVaultNoteMapInfo();
      let frag = document.createDocumentFragment();

      for (let j = 0; j < linesOutput.length; j++) {
        let sp = document.createElement("span");
        let lineText = linesOutput[j];

        this.renderLineContent(sp, lineText, noteMapInfo);

        frag.appendChild(sp);
        if (j < linesOutput.length - 1) {
          frag.appendChild(document.createTextNode("\n"));
        }
      }
      codeEl.appendChild(frag);
    } catch (err) {
      console.error("[ASCII Tree EX] Safe vertical render caught exception:", err);
      this._renderEmptyBlockPlaceholder(containerEl, "v");
    }
  }

  /* ── 5.8 Render Engine C: Synoptic Key Diagram (tree-k) ── */
  _renderTreeK(sourceText, containerEl, ctx, dashCount) {
    try {
      let { autoAppendSlash: o } = this.settings;
      let styleKey = this.settings.treeStyle || "classic";
      let symK = SYNOPTIC_SYMBOLS[styleKey] || SYNOPTIC_SYMBOLS.classic;

      let T = sourceText.split("\n");
      let v = 1 / 0;

      for (let n of T)
        if (n.trim() !== "") {
          let c = n.match(/^([\t ]*)/);
          c && c[1].length < v && (v = c[1].length);
        }

      let C = "";
      v !== 1 / 0 &&
        v > 0 &&
        (C = (T.find((n) => n.trim() !== "")?.slice(0, v)) || "");

      let m = T.map((n) => (n.startsWith(C) ? n.slice(C.length) : n)).map((n) => {
        let c = n.match(/^([\t ]*)((?:[-*+─—–‒•⁃])|\d+\.)\s*(.*)$/);
        if (c) {
          let f = c[1],
            k = (f.match(/\t/g) || []).length,
            d = (f.match(/ /g) || []).length,
            x = k + Math.floor(d / 4);
          return x++, { level: x, text: c[3] ? c[3].trim() : "" };
        }
        let g = n.match(/^(=+)\s?(.*)$/);
        return g
          ? { level: g[1].length, text: g[2] ? g[2].trim() : "" }
          : { level: 0, text: n ? n.trim() : "" };
      });

      let items = m.filter((n) => n.text !== "");
      if (items.length === 0) {
        return this._renderEmptyBlockPlaceholder(containerEl, "k");
      }

      let nodes = items.map((it, idx) => ({
        id: idx,
        level: it.level,
        text: it.text,
        children: [],
        parent: null,
        depth: 0,
        startY: 0,
        endY: 0,
        centerY: 0,
        visLen: this.getVisibleTextLength(it.text)
      }));

      let stack = [];
      for (let node of nodes) {
        while (stack.length > 0 && stack[stack.length - 1].level >= node.level) {
          stack.pop();
        }
        if (stack.length > 0) {
          let parentNode = stack[stack.length - 1];
          parentNode.children.push(node);
          node.parent = parentNode;
        }
        stack.push(node);
      }

      let roots = nodes.filter((n) => n.parent === null);

      let setDepth = (node, d) => {
        node.depth = d;
        for (let c of node.children) {
          setDepth(c, d + 1);
        }
      };
      for (let root of roots) {
        setDepth(root, 0);
      }

      if (o) {
        for (let node of nodes) {
          if (node.children.length > 0 && !node.text.endsWith("/")) {
            node.text += "/";
            node.visLen = this.getVisibleTextLength(node.text);
          }
        }
      }

      // 1. Assign rows Y bottom-up
      let currentLeafY = 0;
      let assignRows = (node) => {
        if (node.children.length === 0) {
          node.startY = currentLeafY;
          node.endY = currentLeafY;
          node.centerY = currentLeafY;
          currentLeafY += 2;
        } else {
          for (let child of node.children) {
            assignRows(child);
          }
          let firstChild = node.children[0];
          let lastChild = node.children[node.children.length - 1];
          node.startY = firstChild.startY;
          node.endY = lastChild.endY;
          node.centerY = Math.floor((firstChild.centerY + lastChild.centerY) / 2);
        }
      };
      for (let root of roots) {
        assignRows(root);
      }

      // 2. Compute fixed column X per level (Straight vertical column per depth)
      let maxDepth = Math.max(...nodes.map((n) => n.depth));
      let maxLenByDepth = new Map();
      for (let d = 0; d <= maxDepth; d++) {
        let depthNodes = nodes.filter((n) => n.depth === d);
        let maxL = depthNodes.length > 0 ? Math.max(...depthNodes.map((n) => n.visLen)) : 0;
        maxLenByDepth.set(d, maxL);
      }

      let colX = new Map();
      let curX = 0;
      let dashPad = Math.max(1, dashCount);
      for (let d = 0; d <= maxDepth; d++) {
        colX.set(d, curX);
        let len = maxLenByDepth.get(d) || 0;
        curX += len + dashPad + 2 + dashPad;
      }

      let totalRows = Math.min(currentLeafY + 2, 500);
      let calculatedMaxX = (colX.get(maxDepth) || 0) + (maxLenByDepth.get(maxDepth) || 0) + 4;
      let maxColX = Math.min(Math.max(calculatedMaxX, 10), 2000);

      let grid = Array.from({ length: totalRows }, () => Array(maxColX + 2).fill(" "));

      // 1. Draw node text lines directly into grid
      for (let node of nodes) {
        let nodeX = colX.get(node.depth) || 0;
        let r = node.centerY;
        let text = node.text;
        for (let k = 0; k < text.length; k++) {
          this.safeSetGrid(grid, r, nodeX + k, text[k], maxColX);
        }
      }

      // 2. Draw brace symbols and connector lines (only over empty spaces)
      for (let node of nodes) {
        if (node.children.length > 0) {
          let depth = node.depth;
          let nodeX = colX.get(depth);
          let nextColX = colX.get(depth + 1);

          let firstChild = node.children[0];
          let lastChild = node.children[node.children.length - 1];

          let topY = firstChild.centerY;
          let botY = lastChild.centerY;
          let midY = node.centerY;

          let braceX = nodeX + (maxLenByDepth.get(depth) || node.visLen) + dashPad;

          let textEndX = nodeX + node.visLen;
          for (let x = textEndX; x <= braceX; x++) {
            if (x < maxColX && this.safeGetGrid(grid, midY, x, maxColX) === " ") {
              this.safeSetGrid(grid, midY, x, symK.dash, maxColX);
            }
          }

          let keyCol = braceX + 1;
          if (keyCol < maxColX) {
            if (topY === botY) {
              if (topY < totalRows && this.safeGetGrid(grid, midY, keyCol, maxColX) === " ") {
                this.safeSetGrid(grid, midY, keyCol, symK.dash, maxColX);
              }
            } else {
              if (topY < totalRows && this.safeGetGrid(grid, topY, keyCol, maxColX) === " ") {
                this.safeSetGrid(grid, topY, keyCol, symK.topCorner, maxColX);
              }
              if (botY < totalRows && this.safeGetGrid(grid, botY, keyCol, maxColX) === " ") {
                this.safeSetGrid(grid, botY, keyCol, symK.bottomCorner, maxColX);
              }
              for (let r = topY + 1; r < botY; r++) {
                if (r < totalRows && this.safeGetGrid(grid, r, keyCol, maxColX) === " ") {
                  this.safeSetGrid(grid, r, keyCol, (r === midY) ? symK.cusp : symK.stem, maxColX);
                }
              }
            }
          }

          let outDashStart = keyCol + 1;
          for (let child of node.children) {
            let cY = child.centerY;
            for (let x = outDashStart; x < nextColX; x++) {
              if (x < maxColX && cY < totalRows && this.safeGetGrid(grid, cY, x, maxColX) === " ") {
                this.safeSetGrid(grid, cY, x, symK.dash, maxColX);
              }
            }
          }
        }
      }

      let linesOutput = [];
      for (let r = 0; r < totalRows; r++) {
        let lineStr = grid[r].join("").replace(/\s+$/, "");
        linesOutput.push(lineStr);
      }

      while (linesOutput.length > 0 && linesOutput[linesOutput.length - 1] === "") {
        linesOutput.pop();
      }

      if (linesOutput.length === 0) {
        return this._renderEmptyBlockPlaceholder(containerEl, "k");
      }

      containerEl.empty();
      let preEl = containerEl.createEl("pre");
      preEl.addClass("ascii-tree-block");
      preEl.addClass("ascii-tree-k");
      if (this.settings.centerTreeK) {
        preEl.addClass("ascii-tree-center");
      }

      if (this.settings.enableLinkHover) {
        preEl.addClass("ascii-tree-hover-" + (this.settings.linkHoverStyle || "bold"));
      }

      let codeEl = preEl.createEl("code");
      let noteMapInfo = this.getVaultNoteMapInfo();
      let frag = document.createDocumentFragment();

      for (let j = 0; j < linesOutput.length; j++) {
        let sp = document.createElement("span");
        let lineText = linesOutput[j];

        this.renderLineContent(sp, lineText, noteMapInfo);

        frag.appendChild(sp);
        if (j < linesOutput.length - 1) {
          frag.appendChild(document.createTextNode("\n"));
        }
      }
      codeEl.appendChild(frag);
    } catch (err) {
      console.error("[ASCII Tree EX] Safe synoptic render caught exception:", err);
      this._renderEmptyBlockPlaceholder(containerEl, "k");
    }
  }

  /* ── 5.9 CSS Variables & Vault Note Mapping Utilities ── */
  applyCSSVars() {
    let root = document.documentElement;
    let spacing = this.settings.titleSpacing ?? 12;
    root.style.setProperty("--ascii-tree-title-font-size", this.settings.titleFontSize || "1.15em");
    root.style.setProperty("--ascii-tree-title-margin-bottom", spacing + "px");
  }

  rerenderAllBlocks() {
    for (let [containerEl, data] of this.renderedBlocks) {
      if (!containerEl.isConnected) {
        this.renderedBlocks.delete(containerEl);
        continue;
      }
      let sourceText = typeof data === "string" ? data : data.sourceText;
      let mode = typeof data === "object" ? data.mode : null;
      this._renderTree(sourceText, containerEl, null, mode);
    }
  }

  updateHoverClasses() {
    let allPre = document.querySelectorAll("pre.ascii-tree-block");
    for (let pre of allPre) {
      let toRemove = Array.from(pre.classList).filter(c => c.startsWith("ascii-tree-hover-"));
      toRemove.forEach(c => pre.classList.remove(c));
      if (this.settings.enableLinkHover) {
        pre.classList.add("ascii-tree-hover-" + (this.settings.linkHoverStyle || "bold"));
      }
    }
  }

  invalidateNoteMapCache() {
    this._cachedNoteMapInfo = null;
  }

  getVaultNoteMapInfo() {
    if (this._cachedNoteMapInfo) {
      return this._cachedNoteMapInfo;
    }
    let noteMap = new Map();
    let pattern = null;
    try {
      if (this.app && this.app.vault) {
        let files = this.app.vault.getMarkdownFiles ? this.app.vault.getMarkdownFiles() : [];
        for (let file of files) {
          let title = file.basename;
          if (title) noteMap.set(title.toLowerCase(), { display: title, target: file.path });
          let cache = this.app.metadataCache ? this.app.metadataCache.getFileCache(file) : null;
          if (cache && cache.frontmatter && cache.frontmatter.aliases) {
            let aliases = cache.frontmatter.aliases;
            if (typeof aliases === "string") aliases = [aliases];
            if (Array.isArray(aliases)) {
              for (let alias of aliases) {
                if (typeof alias === "string" && alias.trim()) {
                  noteMap.set(alias.trim().toLowerCase(), { display: alias.trim(), target: file.path });
                }
              }
            }
          }
        }
      }
      if (noteMap.size > 0) {
        let keys = Array.from(noteMap.keys()).sort((a, b) => b.length - a.length);
        let escaped = keys.map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
        pattern = new RegExp("(?<![\\w\\[])" + "(" + escaped.join("|") + ")" + "(?![\\w\\]])", "gi");
      }
    } catch (err) {
      console.error("[ASCII Tree EX] Error building vault note map:", err);
    }
    this._cachedNoteMapInfo = { noteMap, pattern };
    return this._cachedNoteMapInfo;
  }

  /* ── 5.10 Markdown Syntax & Link Renderer ── */
  renderLineContent(container, text, noteMapInfo) {
    let wikiLinkRegex = /\[\[([^\]\|]+)(?:\|([^\]]+))?\]\]|\[([^\]]+)\]\(([^\)]+)\)/g;
    let lastIndex = 0;
    let match;
    let { noteMap, pattern } = noteMapInfo || {};

    let processPlainSegment = (plainText) => {
      if (!plainText) return;
      if (!noteMap || noteMap.size === 0 || !pattern) {
        container.appendChild(document.createTextNode(plainText));
        return;
      }
      let reg = new RegExp(pattern.source, pattern.flags);
      let segLastIndex = 0;
      let m;
      let iterations = 0;
      while ((m = reg.exec(plainText)) !== null && iterations++ < 500) {
        if (m.index > segLastIndex) {
          container.appendChild(document.createTextNode(plainText.substring(segLastIndex, m.index)));
        }
        let matchedText = m[0];
        let info = noteMap.get(matchedText.toLowerCase());
        if (!info) {
          container.appendChild(document.createTextNode(matchedText));
        } else {
          let target = info.target;
          let a = container.createEl("a", {
            text: matchedText,
            cls: "internal-link glossary-link",
            attr: { "data-href": target, href: target }
          });
          a.addEventListener("click", (evt) => {
            evt.preventDefault();
            this.app.workspace.openLinkText(target, "", evt.metaKey || evt.ctrlKey);
          });
        }
        segLastIndex = reg.lastIndex;
        if (m.index === reg.lastIndex) {
          reg.lastIndex++;
        }
      }
      if (segLastIndex < plainText.length) {
        container.appendChild(document.createTextNode(plainText.substring(segLastIndex)));
      }
    };

    let wikiIterations = 0;
    while ((match = wikiLinkRegex.exec(text)) !== null && wikiIterations++ < 200) {
      if (match.index > lastIndex) {
        processPlainSegment(text.substring(lastIndex, match.index));
      }
      let target, display;
      if (match[1] !== void 0) {
        target = match[1];
        display = match[2] || match[1];
      } else {
        display = match[3];
        target = match[4];
      }
      let a = container.createEl("a", {
        text: display,
        cls: "internal-link",
        attr: { "data-href": target, href: target }
      });
      a.addEventListener("click", (evt) => {
        evt.preventDefault();
        this.app.workspace.openLinkText(target, "", evt.metaKey || evt.ctrlKey);
      });
      lastIndex = wikiLinkRegex.lastIndex;
      if (match.index === wikiLinkRegex.lastIndex) {
        wikiLinkRegex.lastIndex++;
      }
    }
    if (lastIndex < text.length) {
      processPlainSegment(text.substring(lastIndex));
    }
  }

  /* ── 5.11 Plugin Lifecycle & Event Registrations (onload) ── */
  async onload() {
    await this.loadSettings();
    this.applyCSSVars();
    this.addSettingTab(new E(this.app, this));

    if (this.app && this.app.vault) {
      this.registerEvent(this.app.vault.on("create", () => this.invalidateNoteMapCache()));
      this.registerEvent(this.app.vault.on("delete", () => this.invalidateNoteMapCache()));
      this.registerEvent(this.app.vault.on("rename", () => this.invalidateNoteMapCache()));
    }
    if (this.app && this.app.metadataCache) {
      this.registerEvent(this.app.metadataCache.on("changed", () => this.invalidateNoteMapCache()));
    }
    this.registerMarkdownCodeBlockProcessor("tree", (sourceText, containerEl, ctx) => {
      this.treeProcessor(sourceText, containerEl, ctx, null);
    });
    this.registerMarkdownCodeBlockProcessor("tree-v", (sourceText, containerEl, ctx) => {
      this.treeProcessor(sourceText, containerEl, ctx, "v");
    });
    this.registerMarkdownCodeBlockProcessor("tree-k", (sourceText, containerEl, ctx) => {
      this.treeProcessor(sourceText, containerEl, ctx, "k");
    });
    this.addCommand({
      id: "convert-to-tree-block",
      name: "Convert selection to default tree code block (tree)",
      editorCallback: (e) => { this.convertSelectionToTreeBlock(e, null); }
    });
    this.addCommand({
      id: "convert-to-tree-v-block",
      name: "Convert selection to vertical organigram block (tree-v)",
      editorCallback: (e) => { this.convertSelectionToTreeBlock(e, "v"); }
    });
    this.addCommand({
      id: "convert-to-tree-k-block",
      name: "Convert selection to synoptic diagram block (tree-k)",
      editorCallback: (e) => { this.convertSelectionToTreeBlock(e, "k"); }
    });
    this.addCommand({
      id: "remove-tree-block",
      name: "Convert tree block back to text",
      editorCallback: (e) => { this.removeTreeBlock(e); }
    });
    this.addCommand({
      id: "toggle-tree-block",
      name: "Toggle tree block",
      editorCallback: (e) => { this.toggleTreeBlock(e); }
    });
  }

  /* ── 5.12 Settings Management & Editor Commands ── */
  async loadSettings() {
    this.settings = Object.assign({}, W, await this.loadData());
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }

  convertSelectionToTreeBlock(e, mode = null) {
    let tag = mode === "v" ? "tree-v" : (mode === "k" ? "tree-k" : "tree");
    let s = e.getSelection();
    if (s) {
      e.replaceSelection("```" + tag + "\n" + s + "\n```");
    } else {
      let o = e.getCursor().line,
        a = e.getLine(o),
        r = { line: o, ch: 0 },
        t = { line: o, ch: a.length };
      e.replaceRange("```" + tag + "\n" + a + "\n```", r, t);
      e.setCursor(o + 1, a.length);
    }
  }

  removeTreeBlock(e) {
    let s = e.getCursor(),
      o = e.getValue().split("\n"),
      a = s.line,
      i = -1,
      r = -1;
    for (let t = a; t >= 0; t--) {
      if (o[t].trim().match(/^```tree(?:-[vk])?\s*$/)) { i = t; break; }
      if (t !== a && o[t].trim().match(/^```/)) break;
    }
    if (i !== -1)
      for (let t = i + 1; t < o.length; t++)
        if (o[t].trim() === "```") { r = t; break; }
    if (i !== -1 && r !== -1 && a >= i && a <= r) {
      let t = o.slice(i + 1, r).join("\n"),
        S = { line: i, ch: 0 },
        w = { line: r, ch: o[r].length };
      e.replaceRange(t, S, w);
      e.setCursor(i, 0);
    }
  }

  toggleTreeBlock(e) {
    this.isInsideTreeBlock(e) ? this.removeTreeBlock(e) : this.convertSelectionToTreeBlock(e);
  }

  isInsideTreeBlock(e) {
    let s = e.getCursor(),
      o = e.getValue().split("\n"),
      a = s.line,
      i = -1,
      r = -1;
    for (let t = a; t >= 0; t--) {
      if (o[t].trim().match(/^```tree(?:-[vk])?\s*$/)) { i = t; break; }
      if (t !== a && o[t].trim().match(/^```/)) break;
    }
    if (i !== -1)
      for (let t = i + 1; t < o.length; t++)
        if (o[t].trim() === "```") { r = t; break; }
    return i !== -1 && r !== -1 && a >= i && a <= r;
  }
};

/* ========================================================================
   SECTION 6: SETTINGS TAB USER INTERFACE (SettingTab E)
   ======================================================================== */
var E = class extends u.PluginSettingTab {
  constructor(e, s) {
    super(e, s);
    this.plugin = s;
  }

  display() {
    let { containerEl: e } = this;
    e.empty();
    let T = (key) => this.plugin.t(key);

    /* ── Plugin Header ───────────────────────────────────── */
    let headerDiv = e.createEl("div");
    headerDiv.style.marginBottom = "18px";
    headerDiv.createEl("h2", { text: "ASCII Tree Generator Extended" });
    let authorP = headerDiv.createEl("p", { cls: "setting-item-description" });
    authorP.style.marginTop = "-6px";
    authorP.createEl("span", { text: "Desarrollado por " });
    authorP.createEl("a", { text: "Baalgarthem", href: "https://github.com/Baalgarthem" });

    /* ── Language selector — always first ─────────────────── */
    new u.Setting(e)
      .setName(T("langSettingName"))
      .setDesc(T("langSettingDesc"))
      .addDropdown((s) =>
        s
          .addOption("es", T("langEs"))
          .addOption("en", T("langEn"))
          .setValue(this.plugin.settings.language || "es")
          .onChange(async (l) => {
            this.plugin.settings.language = l;
            await this.plugin.saveSettings();
            // Refresh settings panel immediately with new language
            this.display();
          })
      );

    /* ── Section: Available Diagram Types ─────────────────── */
    e.createEl("h3", { text: T("sectionBlockTypes") });
    let infoDiv = e.createEl("div", { cls: "setting-item-description" });
    infoDiv.style.marginBottom = "14px";
    infoDiv.style.lineHeight = "1.5";
    infoDiv.createEl("p", { text: T("blockTypesDesc") });
    let ul = infoDiv.createEl("ul");
    ul.style.marginTop = "6px";
    ul.style.paddingLeft = "20px";
    ul.createEl("li", { text: T("infoTree") });
    ul.createEl("li", { text: T("infoTreeV") });
    ul.createEl("li", { text: T("infoTreeK") });

    /* ── Section: Tree Appearance ─────────────────────────── */
    e.createEl("h3", { text: T("sectionAppearance") });

    new u.Setting(e)
      .setName(T("treeStyleName"))
      .setDesc(T("treeStyleDesc"))
      .addDropdown((s) =>
        s
          .addOption("classic",   T("styleClassic"))
          .addOption("rounded",   T("styleRounded"))
          .addOption("heavy",     T("styleHeavy"))
          .addOption("double",    T("styleDouble"))
          .addOption("dotted",    T("styleDotted"))
          .addOption("slim",      T("styleSlim"))
          .addOption("asciiplus", T("styleAsciiplus"))
          .addOption("arrows",    T("styleArrows"))
          .setValue(this.plugin.settings.treeStyle || "classic")
          .onChange(async (l) => {
            this.plugin.settings.treeStyle = l;
            await this.plugin.saveSettings();
            this.plugin.rerenderAllBlocks();
          })
      );

    new u.Setting(e)
      .setName(T("dashCountName"))
      .setDesc(T("dashCountDesc"))
      .addSlider((s) =>
        s
          .setLimits(1, 10, 1)
          .setValue(this.plugin.settings.dashCount)
          .setDynamicTooltip()
          .onChange(async (l) => {
            this.plugin.settings.dashCount = l;
            await this.plugin.saveSettings();
            this.plugin.rerenderAllBlocks();
          })
      );

    new u.Setting(e)
      .setName(T("autoSlashName"))
      .setDesc(T("autoSlashDesc"))
      .addToggle((s) =>
        s.setValue(this.plugin.settings.autoAppendSlash).onChange(async (l) => {
          this.plugin.settings.autoAppendSlash = l;
          await this.plugin.saveSettings();
          this.plugin.rerenderAllBlocks();
        })
      );

    /* ── Section: Title Line ──────────────────────────────── */
    e.createEl("h3", { text: T("sectionTitle") });

    new u.Setting(e)
      .setName(T("titleFormatName"))
      .setDesc(T("titleFormatDesc"))
      .addToggle((s) =>
        s.setValue(this.plugin.settings.enableTitleFormat).onChange(async (l) => {
          this.plugin.settings.enableTitleFormat = l;
          await this.plugin.saveSettings();
          this.plugin.rerenderAllBlocks();
        })
      );

    new u.Setting(e)
      .setName(T("titleSpacingName"))
      .setDesc(T("titleSpacingDesc"))
      .addSlider((s) =>
        s
          .setLimits(0, 40, 1)
          .setValue(this.plugin.settings.titleSpacing ?? 12)
          .setDynamicTooltip()
          .onChange(async (l) => {
            this.plugin.settings.titleSpacing = l;
            await this.plugin.saveSettings();
            this.plugin.applyCSSVars();
          })
      );

    /* ── Section: Link Hover ──────────────────────────────── */
    e.createEl("h3", { text: T("sectionHover") });

    new u.Setting(e)
      .setName(T("hoverEnableName"))
      .setDesc(T("hoverEnableDesc"))
      .addToggle((s) =>
        s.setValue(this.plugin.settings.enableLinkHover).onChange(async (l) => {
          this.plugin.settings.enableLinkHover = l;
          await this.plugin.saveSettings();
          this.plugin.updateHoverClasses();
        })
      );

    new u.Setting(e)
      .setName(T("hoverStyleName"))
      .setDesc(T("hoverStyleDesc"))
      .addDropdown((s) =>
        s
          .addOption("bold",      T("hoverBold"))
          .addOption("border",    T("hoverBorder"))
          .addOption("underline", T("hoverUnderline"))
          .addOption("highlight", T("hoverHighlight"))
          .addOption("glow",      T("hoverGlow"))
          .addOption("pill",      T("hoverPill"))
          .addOption("neon",      T("hoverNeon"))
          .addOption("ghost",     T("hoverGhost"))
          .addOption("boldglow",  T("hoverBoldglow"))
          .setValue(this.plugin.settings.linkHoverStyle || "bold")
          .onChange(async (l) => {
            this.plugin.settings.linkHoverStyle = l;
            await this.plugin.saveSettings();
            this.plugin.updateHoverClasses();
          })
      );
  }
};

/* nosourcemap */